export const FETCH_BRANDS = 'FETCH_BRANDS';
export const FETCH_BRANDS_SUCCESS = 'FETCH_BRANDS_SUCCESS';
export const FETCH_BRANDS_ERROR = 'FETCH_BRANDS_ERROR';

export const FETCH_BRAND_WITH_CHOCOLATES = 'FETCH_BRAND_WITH_CHOCOLATES';
export const FETCH_BRAND_WITH_CHOCOLATES_SUCCESS = 'FETCH_BRAND_WITH_CHOCOLATES_SUCCESS';
export const FETCH_BRAND_WITH_CHOCOLATES_ERROR = 'FETCH_BRAND_WITH_CHOCOLATES_ERROR';
