export const FETCH_CHOCOLATES = 'FETCH_CHOCOLATES';
export const FETCH_CHOCOLATES_SUCCESS = 'FETCH_CHOCOLATES_SUCCESS';
export const FETCH_CHOCOLATES_ERROR = 'FETCH_CHOCOLATES_ERROR';

export const FETCH_CHOCOLATE = 'FETCH_CHOCOLATE';
export const FETCH_CHOCOLATE_SUCCESS = 'FETCH_CHOCOLATE_SUCCESS';
export const FETCH_CHOCOLATE_ERROR = 'FETCH_CHOCOLATE_ERROR';

export const ADD_CHOCOLATE = 'ADD_CHOCOLATE';
export const ADD_CHOCOLATE_SUCCESS = 'ADD_CHOCOLATE_SUCCESS';
export const ADD_CHOCOLATE_ERROR = 'ADD_CHOCOLATE_ERROR';